# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orlojctl < Formula
  desc "CLI for Orloj — multi-agent AI orchestration runtime"
  homepage "https://github.com/OrlojHQ/orloj"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.10.0/orlojctl_v0.10.0_darwin_amd64.tar.gz"
      sha256 "a042912944d396308f0fa75e94e4b8791c3b9b2f689c58d1c423dc8806a5c786"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.10.0/orlojctl_v0.10.0_darwin_arm64.tar.gz"
      sha256 "88946877d627748f39bf53074dca1b00b7924cfaa31bc829f365e0c2509961cc"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.10.0/orlojctl_v0.10.0_linux_amd64.tar.gz"
      sha256 "08010368942d8574822802d80aa4c84983c44eae091c1fc39b1c3ea713229603"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.10.0/orlojctl_v0.10.0_linux_arm64.tar.gz"
      sha256 "a78a08ca8bf0d495c30046fd3ba445a83a62a718adc01e47a4b8826fc8c31cb9"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  test do
    system "#{bin}/orlojctl", "version"
  end
end
