# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orlojctl < Formula
  desc "CLI for Orloj — multi-agent AI orchestration runtime"
  homepage "https://github.com/OrlojHQ/orloj"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.16.0/orlojctl_v0.16.0_darwin_amd64.tar.gz"
      sha256 "3c46b0f25b9f87fa032436343175968ac4a63f8e8886b909437f6faacc71fdf6"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.16.0/orlojctl_v0.16.0_darwin_arm64.tar.gz"
      sha256 "1329188fb66cb9a31395a4fa58908cdba0428db329118a3c5cb37405c9e29da2"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.16.0/orlojctl_v0.16.0_linux_amd64.tar.gz"
      sha256 "c63469c47bf9580b18fd97465393018febeafae2ab98331dd0902c28841d9ec8"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.16.0/orlojctl_v0.16.0_linux_arm64.tar.gz"
      sha256 "9e0e97c3ecee4d0e1342ba1205165960ba8785305a92819ba7ba94e286a6f8ef"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  test do
    system "#{bin}/orlojctl", "version"
  end
end
