# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orlojctl < Formula
  desc "CLI for Orloj — multi-agent AI orchestration runtime"
  homepage "https://github.com/OrlojHQ/orloj"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.4.0/orlojctl_v0.4.0_darwin_amd64.tar.gz"
      sha256 "76c963d999311b619f8e54802d81b12b24aa87a839d192b29e9cd865894bc90b"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.4.0/orlojctl_v0.4.0_darwin_arm64.tar.gz"
      sha256 "81aeee07f325399390cb885a81217339b780f9e4120aa2832dd35c4b04258d21"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.4.0/orlojctl_v0.4.0_linux_amd64.tar.gz"
      sha256 "aefee57986bfffb039d28dbc5951834c95d6468e42175fd01cb5369bd8cb508c"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.4.0/orlojctl_v0.4.0_linux_arm64.tar.gz"
      sha256 "ef7b503a8bf0b00857a1c6d69f717df9c157cb822dd975536074c2ddaae93de1"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  test do
    system "#{bin}/orlojctl", "version"
  end
end
