# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orloj < Formula
  desc "CLI for Orloj — multi-agent AI orchestration runtime"
  homepage "https://github.com/OrlojHQ/orloj"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.3.0/orlojctl_v0.3.0_darwin_amd64.tar.gz"
      sha256 "dff3e4d6a870f3b287e17258b98b80a31ddb73d47a3dac02c8534466b9f7c54a"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.3.0/orlojctl_v0.3.0_darwin_arm64.tar.gz"
      sha256 "31ccb4b72ec364482a83d0cbbeecbddd1f806f11c0a65a352ec69466dcb4ae52"

      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.3.0/orlojctl_v0.3.0_linux_amd64.tar.gz"
      sha256 "c8571034c193052077933d0fc34461007f92e01f10c075f769dfa6deb62ed40e"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrlojHQ/orloj/releases/download/v0.3.0/orlojctl_v0.3.0_linux_arm64.tar.gz"
      sha256 "56c503e82c3025620406798180c642b49bfb767fc43d7167151bc960da751329"
      define_method(:install) do
        bin.install "orlojctl"
      end
    end
  end

  test do
    system "#{bin}/orlojctl", "version"
  end
end
